In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.shape

(5,)

In [13]:
#multidimentional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,5,4]
arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 5, 4]])

In [7]:
arr.shape

(3, 5)

In [8]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 5, 4]])

In [9]:
arr.shape

(3, 5)

In [10]:
#indexing
arr=np.array([1,2,3,4,5,6,7,8,9])

In [11]:
arr[3]

np.int64(4)

In [14]:
#indexing with two dimensional array
arr[1:,3:] #row index and column index

array([[5, 6],
       [5, 4]])

In [15]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [18]:
arr[0:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [19]:
arr=np.arange(0,10) #picks up all elements btw 0-10
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr=np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [23]:
np.linspace(1,10,50) #equally spaced 50 points btw 1-10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [25]:
#copy() function and broadcasting
arr[3:]=100
arr

array([  0,   2,   4, 100, 100])

In [26]:
arr1=arr

In [27]:
arr1[3:]=500
print(arr1)

[  0   2   4 500 500]


In [29]:
arr #both arrays updated

array([  0,   2,   4, 500, 500])

In [32]:
#conditions useful in EDA
val=2
arr<2

array([ True, False, False, False, False])

In [34]:
arr*2 #can do for all operations

array([   0,    4,    8, 1000, 1000])

In [35]:
arr[arr<3]

array([0, 2])

In [37]:
#creating arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [41]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
#random distribution
np.random.rand(3,3) #linear graph

array([[0.54359845, 0.10888129, 0.04335591],
       [0.20517832, 0.49757908, 0.30558359],
       [0.16266338, 0.63373433, 0.35181455]])

In [44]:
arr_ex=np.random.randn(4,4) #curve graph and includes -ve values
arr_ex

array([[-0.29868456, -1.43091537,  0.96427469,  1.52043897],
       [ 0.26440688,  0.52901357, -0.23703299,  0.77499409],
       [ 1.60746055,  1.23729549,  0.2446907 ,  1.33179344],
       [-2.47170421,  1.1299396 ,  0.66156874,  1.42714861]])